import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/utils/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import GetProfile from "./(systemTasks)/tasks/GetProfile";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bayan Masters Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider>
          <div className="bg-gray-100/50 dark:bg-zinc-950">{children}</div>

          <GetProfile />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
