import { Sidebar } from "@/components/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/utils/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider>
        <div className="min-h-screen flex overflow-hidden bg-zinc-900">
          <Sidebar />
          <div
            id="main-content"
            className={`w-full ml-64  transition-all duration-300`}
          >
            <Navbar/>
            <div className="p-6">
            {children}
            </div>
          </div>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
